# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release
      
environment:
  # enable remotes
  USE_RTOOLS: true
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - tk
  homebrew:
    packages:
      - php
      - imagemagick
      - pkg-config
    update: true  

r_packages:
  - igraph
  - utils
  - mvtnorm
  - Matrix
  - matrixcalc
  - graphics
  - knitr
  - rmarkdown
  - animation
  - testthat
  - gplots
  - devtools
  - covr

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'

ignore:
  - LICENSE
  - vignettes/*html
