# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

environment:
  # enable remotes
  USE_RTOOLS: true

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt-get install tk

r_packages:
  - igraph
  - utils
  - mvtnorm
  - Matrix
  - matrixcalc
  - graphics
  - knitr
  - rmarkdown
  - animation
  - testthat
  - gplots
  - devtools
  - covr

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'

ignore:
  - LICENSE
  - vignettes/*html
