# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# enable remotes
r_github_packages:
- TomKellyGenetics/plot.igraph
- TomKellyGenetics/heatmap.2

environment:
  # enable remotes
  USE_RTOOLS: true
