---
title: "Simulating network graph structure in continous data"
author: "Tom Kelly"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Simulating large network graph structure in continous data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

##Install dependencies for Demonstration

```{r, message=F, warning=F}
library('mvtnorm')
library("igraph")
library("devtools")
devtools::install_github("TomKellyGenetics/plot.igraph")
library("plot.igraph")
devtools::install_github("TomKellyGenetics/heatmap.2x")
library("heatmap.2x")
devtools::install_github("TomKellyGenetics/graphsim")
library("graphsim")
Rprof("test_graph_network_large.out", interval = 0.001, memory.profiling = F)
#Rprof("test_graph_network_large.mem.out", interval = 0.001, memory.profiling = T)
```

##set up simulated graphs

```{r, out.width = '50%', out.height  = '50%', fig.align='center'}
graph_tree <- make_tree(500, 3)
plot_directed(graph_tree, layout = layout.kamada.kawai)
```

#Generated simulated expression data from graph

##Adjacency matrix

```{r, out.width = '50%', out.height  = '50%', fig.align='center'}
adj_mat <- make_adjmatrix_graph(graph_tree)
heatmap.2x(make_adjmatrix_graph(graph_tree), scale = "none", trace = "none", col = colorpanel(3, "grey75", "white", "blue"), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(make_adjmatrix_graph(graph_tree, directed = T), scale = "none", trace = "none", col = colorpanel(3, "grey75", "white", "blue"), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
comm_mat <- make_commonlink_graph(graph_tree)
heatmap.2x(make_commonlink_graph(graph_tree), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
```

##Distance matrix

```{r, out.width = '50%', out.height  = '50%', fig.align='center'}
shortest.paths(graph_tree)
heatmap.2x(shortest.paths(graph_tree), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
(diameter(graph_tree)-shortest.paths(graph_tree))/diameter(graph_tree)
heatmap.2x((diameter(graph_tree)-shortest.paths(graph_tree))/diameter(graph_tree), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
make_distance_graph(graph_tree, absolute = F)
make_distance_graph(graph_tree, absolute = T)
```

##Sigma matrix

```{r, out.width = '50%', out.height  = '50%', fig.align='center'}
#sigma from adj mat
make_sigma_mat_graph(graph_tree, 0.8)
heatmap.2x(make_sigma_mat_graph(graph_tree, 0.8), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
#sigma from comm mat
make_sigma_mat_graph(graph_tree, 0.8, comm = T)
heatmap.2x(make_sigma_mat_graph(graph_tree, 0.8, comm = T), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
# sigma from distance matrix
make_sigma_mat_dist_graph(graph_tree, 0.8, absolute = T)
make_sigma_mat_dist_graph(graph_tree, 0.8, absolute = F)
heatmap.2x(make_sigma_mat_dist_graph(graph_tree, 0.8, absolute = T), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(make_sigma_mat_dist_graph(graph_tree, 0.8, absolute = F), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
```

#Simulated expression and observed correlation

```{r, out.width = '50%', out.height  = '50%', fig.align='center'}
#simulate expression data
#adj mat
expr <- generate_expression(100, graph_tree, cor = 0.8, mean = 0, comm =F) # unable to generate from adj mat ## fixed with positive definite correction
heatmap.2x(expr, scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(cor(t(expr)), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
#comm mat
expr <- generate_expression(100, graph_tree, cor = 0.8, mean = 0, comm =T) #expression from comm mat
heatmap.2x(expr, scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(cor(t(expr)), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
#absolute dist
expr<- generate_expression(100, graph_tree, cor = 0.8, mean = 0, comm = F, dist = T, absolute = T) # unable to generate from adj mat ## fixed PD
heatmap.2x(expr, scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(cor(t(expr)), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
# relative dist
expr<- generate_expression(100, graph_tree, cor = 0.8, mean = 0, comm = F, dist = T, absolute = F)
heatmap.2x(expr, scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
heatmap.2x(cor(t(expr)), scale = "none", trace = "none", col = bluered(50), colsep = 1:length(V(graph_tree)), rowsep = 1:length(V(graph_tree)))
```
