version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    environment:
      R_LIBS: ~/R/Library
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache--
            - r-pkg-cache--
      - checkout
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            Rscript -e 'install.packages(c("mvtnorm", "matrixcalc"))'
      - run:
          name: Install dependencies
          command: |
            Rscript \
            -e 'if (!requireNamespace("utils", quietly = TRUE)) install.packages("utils")' \
            -e 'if (!requireNamespace("igraph", quietly = TRUE)) install.packages("igraph")' \
            -e 'if (!requireNamespace("RColorBrewer", quietly = TRUE)) install.packages("RColorBrewer")' \
            -e 'if (!requireNamespace("mvtnorm", quietly = TRUE)) install.packages("mvtnorm")' \
            -e 'if (!requireNamespace("matrixcalc", quietly = TRUE)) install.packages("matrixcalc")' \
            -e 'if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr")' \
            -e 'if (!requireNamespace("rmarkdown", quietly = TRUE)) install.packages("rmarkdown")' \
            -e 'if (!requireNamespace("animation", quietly = TRUE)) install.packages("animation")' \
            -e 'if (!requireNamespace("testthat", quietly = TRUE)) install.packages("testthat")' \
            -e 'if (!requireNamespace("gplots", quietly = TRUE)) install.packages("mgplots")' \
            -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --as-cran --no-manual *tar.gz
      - store_artifacts:
          path: graphsim.Rcheck/
      - save_cache:
          key: r-pkg-cache--
          paths:
            - "~/R/Library"
